<?php
			if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array(
                    'key' => 'group_6297994f65112',
                    'title' => 'Page Design',
                    'fields' => array(
                        array(
                            'key' => 'field_62b57e0ac8c7a',
                            'label' => '<font size="+2">Website Informationen</font>',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'field_62b57e71b7366',
                            'label' => 'Logo der Webseite',
                            'name' => 'logo_der_webseite',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'uploader' => '',
                            'acfe_thumbnail' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'library' => 'all',
                        ),
                        array(
                            'key' => 'field_62bc5b46ea1ea',
                            'label' => 'Logo für den Footer',
                            'name' => 'logo_fuer_footer',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'uploader' => '',
                            'acfe_thumbnail' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'library' => 'all',
                        ),
                        array(
                            'key' => 'field_62b57e8ab7367',
                            'label' => 'Favicon der Webseite',
                            'name' => 'favicon_der_webseite',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'uploader' => '',
                            'acfe_thumbnail' => 0,
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'library' => 'all',
                        ),
                        array(
                            'key' => 'field_62b57e275472f',
                            'label' => 'Titel der Webseite',
                            'name' => 'titel_der_webseite',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_62b57e59d0237',
                            'label' => 'Slogen der Webseite',
                            'name' => 'slogen_der_webseite',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_62b1cc17ad63b',
                            'label' => '<font size="+2">Farbgebung</font>',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'field_62b57fc8dee48',
                            'label' => '3D Rockpage Header Hintergrund',
                            'name' => '3d_rockpage_header_hintergrund',
                            'type' => 'color_picker',
                            'instructions' => 'Wenn Sie wollen können sie hier einen anderen Header Hintergrund wählen.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 1,
                            'return_format' => 'string',
                        ),
                        array(
                            'key' => 'field_62b5886863ac2',
                            'label' => '3D Rockpage Header Schriftfarbe',
                            'name' => '3d_rockpage_header_schriftfarbe',
                            'type' => 'color_picker',
                            'instructions' => 'Wenn Sie wollen können sie hier einen anderen Header Hintergrund wählen.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 1,
                            'return_format' => 'string',
                        ),
                        array(
                            'key' => 'field_62b1c243822f8',
                            'label' => '3D Rockpage Hintergrund',
                            'name' => '3d_rockpage_hintergrund',
                            'type' => 'color_picker',
                            'instructions' => 'Wähle hier ob die 3D Rockpage hell oder dunkel im Hintergrund aussehen sollte. (schwarz oder weiß)',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 1,
                            'return_format' => 'string',
                        ),
                        array(
                            'key' => 'field_62b1bb5cdd729',
                            'label' => '3D Rockpage Schriftfarbe',
                            'name' => '3d_rockpage_schriftfarbe',
                            'type' => 'color_picker',
                            'instructions' => 'Bitte wähle hier eine Kontrastreiche Schriftfarbe zu deinen gewählten Hintergrund, um den Text gut zu lesen!',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 1,
                            'return_format' => 'string',
                        ),
                        array(
                            'key' => 'field_62979965648ce',
                            'label' => 'Primere Farbe',
                            'name' => 'primere_farbe',
                            'type' => 'color_picker',
                            'instructions' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 0,
                            'return_format' => 'string',
                        ),
                        array(
                            'key' => 'field_62b1bab8991b6',
                            'label' => 'Sekundäre Farbe',
                            'name' => 'sekundare_farbe',
                            'type' => 'color_picker',
                            'instructions' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 1,
                            'return_format' => 'string',
                        ),
                        array(
                            'key' => 'field_62b1baf4991b8',
                            'label' => 'Akzent Farbe',
                            'name' => 'akzent_farbe',
                            'type' => 'color_picker',
                            'instructions' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'enable_opacity' => 1,
                            'return_format' => 'string',
                        ),
                        array(
                            'key' => 'field_62b967e0638fc',
                            'label' => '<font size="+2">Schriftarten</font>',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'field_62b97f7ff1ff0',
                            'label' => '<font size="+1">Beispiele:</font>',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '<img src="http://www.tutorialspoint.com/images/html.gif" alt="HTML Tutorial" height="150" width="140" />',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'field_62b9680b9959c',
                            'label' => 'Schriftart Überschriften',
                            'name' => 'schriftart_uberschriften',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                '\'Dancing Script\', cursive' => '\'Dancing Script\', cursive',
                                '\'Indie Flower\', cursive' => '\'Indie Flower\', cursive',
                                '\'Roboto\', sans-serif' => '\'Roboto\', sans-serif',
                                '\'Roboto Mono\', monospace' => '\'Roboto Mono\', monospace',
                                '\'Roboto Slab\', serif' => '\'Roboto Slab\', serif',
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_62b9a62473f12',
                            'label' => 'Schriftart Texte',
                            'name' => 'schriftart_texte',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                '\'Roboto\', sans-serif' => '\'Roboto\', sans-serif',
                                '\'Roboto Mono\', monospace' => '\'Roboto Mono\', monospace',
                                '\'Roboto Slab\', serif' => '\'Roboto Slab\', serif',
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_62b9b214d7b6d',
                            'label' => '<font size="+2">Buttons</font>',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'field_62b9b22fd7b6e',
                            'label' => 'Buttonradius',
                            'name' => 'buttonradius',
                            'type' => 'range',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => 50,
                            'step' => 1,
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_62bc227c747e7',
                            'label' => '<font size="+2">Mitarbeiter</font>',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'field_62bc2297747e8',
                            'label' => 'Mitarbeiterfotos Größe (px)',
                            'name' => 'mitarbeiterfotos_grose',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'options_page',
                                'operator' => '==',
                                'value' => '3d-design',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'seamless',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => array(
                        0 => 'permalink',
                        1 => 'block_editor',
                        2 => 'the_content',
                        3 => 'excerpt',
                        4 => 'discussion',
                        5 => 'comments',
                        6 => 'revisions',
                        7 => 'slug',
                        8 => 'author',
                        9 => 'format',
                        10 => 'page_attributes',
                        11 => 'featured_image',
                        12 => 'categories',
                        13 => 'tags',
                        14 => 'send-trackbacks',
                    ),
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                    'acfe_display_title' => '',
                    'acfe_autosync' => '',
                    'acfe_form' => 0,
                    'acfe_meta' => '',
                    'acfe_note' => '',
                ));
                
                endif;		