<?php
			if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array(
                    'key' => 'group_62b44cb7c2f8e',
                    'title' => 'Seiten Struktur',
                    'fields' => array(
                        array(
                            'key' => 'field_62bb086656642',
                            'label' => 'Header (Kopfbereich)',
                            'name' => 'header',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'acfe_seamless_style' => 0,
                            'acfe_group_modal' => 0,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_62bb09f70cad2',
                                    'label' => 'Header',
                                    'name' => 'header',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        '[elementor-template id="1287"]' => 'Logo mittig',
                                        '[elementor-template id="214"]' => 'Logo links',
                                    ),
                                    'default_value' => false,
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'return_format' => 'value',
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_62b44daf13762',
                            'label' => 'Inhaltsbereich (Main)',
                            'name' => 'inhaltsbereich_main',
                            'type' => 'flexible_content',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'acfe_flexible_advanced' => 1,
                            'acfe_flexible_stylised_button' => 0,
                            'acfe_flexible_hide_empty_message' => 0,
                            'acfe_flexible_empty_message' => '',
                            'acfe_flexible_layouts_templates' => 0,
                            'acfe_flexible_layouts_placeholder' => 1,
                            'acfe_flexible_layouts_thumbnails' => 0,
                            'acfe_flexible_layouts_settings' => 0,
                            'acfe_flexible_async' => array(
                            ),
                            'acfe_flexible_add_actions' => array(
                            ),
                            'acfe_flexible_remove_button' => array(
                            ),
                            'acfe_flexible_layouts_state' => 'user',
                            'acfe_flexible_modal_edit' => array(
                                'acfe_flexible_modal_edit_enabled' => '0',
                                'acfe_flexible_modal_edit_size' => 'large',
                            ),
                            'acfe_flexible_modal' => array(
                                'acfe_flexible_modal_enabled' => '0',
                                'acfe_flexible_modal_title' => false,
                                'acfe_flexible_modal_size' => 'full',
                                'acfe_flexible_modal_col' => '4',
                                'acfe_flexible_modal_categories' => false,
                            ),
                            'layouts' => array(
                                'layout_62b6c7bef82ab' => array(
                                    'key' => 'layout_62b6c7bef82ab',
                                    'name' => '360grad_rundgang',
                                    'label' => '360Grad Rundgang',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62b6c7bef82ad',
                                            'label' => 'Bild Überlagerung',
                                            'name' => 'bild_uberlagerung',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '33',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'uploader' => '',
                                            'acfe_thumbnail' => 0,
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'library' => 'all',
                                        ),
                                        array(
                                            'key' => 'field_62b6c7bef82ae',
                                            'label' => 'Farb Überlagerung',
                                            'name' => 'farb_uberlagerung',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                        array(
                                            'key' => 'field_62b6c7bef82af',
                                            'label' => 'Text- Überlagerung',
                                            'name' => 'text-_uberlagerung',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                        array(
                                            'key' => 'field_62b8b0ae41873',
                                            'label' => 'Text- Überlagerungsfarbe',
                                            'name' => 'text-_uberlagerungsfarbe',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 0,
                                            'return_format' => 'string',
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc08c26361a' => array(
                                    'key' => 'layout_62bc08c26361a',
                                    'name' => 'block_text_text',
                                    'label' => 'Block (Text/Text)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc0d945c97d',
                                            'label' => 'Beitrag Content',
                                            'name' => 'beitrag_content',
                                            'type' => 'post_object',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'post_type' => array(
                                                0 => 'rezessionen',
                                                1 => 'mitarbeiter',
                                                2 => 'blognews',
                                                3 => 'produkte',
                                                4 => 'inhalte',
                                            ),
                                            'taxonomy' => '',
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                            'return_format' => 'id',
                                            'save_custom' => 0,
                                            'save_post_status' => 'publish',
                                            'acfe_bidirectional' => array(
                                                'acfe_bidirectional_enabled' => '0',
                                            ),
                                            'ui' => 1,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62b44e92504d0' => array(
                                    'key' => 'layout_62b44e92504d0',
                                    'name' => 'content_bild_rechts',
                                    'label' => 'Block (Text/Bild)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62b44e92504d1',
                                            'label' => 'Beitrag Content',
                                            'name' => 'beitrag_content',
                                            'type' => 'post_object',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '80',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'post_type' => array(
                                                0 => 'mitarbeiter',
                                                1 => 'rezessionen',
                                                2 => 'blognews',
                                                3 => 'inhalte',
                                                4 => 'produkte',
                                            ),
                                            'taxonomy' => '',
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                            'return_format' => 'id',
                                            'save_custom' => 0,
                                            'save_post_status' => 'publish',
                                            'acfe_bidirectional' => array(
                                                'acfe_bidirectional_enabled' => '0',
                                            ),
                                            'ui' => 1,
                                        ),
                                        array(
                                            'key' => 'field_62b56d43b4893',
                                            'label' => 'Farbgebung',
                                            'name' => 'farbgebung',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '20',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62b54aa591096' => array(
                                    'key' => 'layout_62b54aa591096',
                                    'name' => 'content_bild_links',
                                    'label' => 'Block (Bild/Text)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62b54aa591097',
                                            'label' => 'Beitrag Content',
                                            'name' => 'beitrag_content',
                                            'type' => 'post_object',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '80',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'post_type' => array(
                                                0 => 'mitarbeiter',
                                                1 => 'blognews',
                                                2 => 'inhalte',
                                                3 => 'rezessionen',
                                                4 => 'produkte',
                                            ),
                                            'taxonomy' => '',
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                            'return_format' => 'id',
                                            'save_custom' => 0,
                                            'save_post_status' => 'publish',
                                            'acfe_bidirectional' => array(
                                                'acfe_bidirectional_enabled' => '0',
                                            ),
                                            'ui' => 1,
                                        ),
                                        array(
                                            'key' => 'field_62b56d7b865f4',
                                            'label' => 'Farbgebung',
                                            'name' => 'farbgebung',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '20',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62b56d9e865f5' => array(
                                    'key' => 'layout_62b56d9e865f5',
                                    'name' => 'page_trenner',
                                    'label' => 'Seiten Trenner',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62b56dae865f6',
                                            'label' => 'Text',
                                            'name' => 'text',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '33',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                        array(
                                            'key' => 'field_62b56dd1865f7',
                                            'label' => 'Hintergrund Bild',
                                            'name' => 'hintergrund_bild',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '33',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'uploader' => '',
                                            'acfe_thumbnail' => 0,
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'library' => 'all',
                                        ),
                                        array(
                                            'key' => 'field_62b56df4865f8',
                                            'label' => 'Hintergrundfarbe',
                                            'name' => 'hintergrundfarbe',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                        array(
                                            'key' => 'field_62b6c1080376a',
                                            'label' => 'Textfarbe',
                                            'name' => 'textfarbe',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                        array(
                                            'key' => 'field_62bc18c2a6b99',
                                            'label' => 'Mindesthöhe',
                                            'name' => 'mindesthohe',
                                            'type' => 'range',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'min' => 10,
                                            'max' => 1440,
                                            'step' => '',
                                            'prepend' => '',
                                            'append' => '',
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc2e7e7d15c' => array(
                                    'key' => 'layout_62bc2e7e7d15c',
                                    'name' => 'design_trenner',
                                    'label' => 'Design Trenner (Bild/Text)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc2e7e7d15d',
                                            'label' => 'Text',
                                            'name' => 'dt_text',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '33',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                        array(
                                            'key' => 'field_62bc2e7e7d15e',
                                            'label' => 'Bild',
                                            'name' => 'dt_bild',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '33',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'uploader' => '',
                                            'acfe_thumbnail' => 0,
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'library' => 'all',
                                        ),
                                        array(
                                            'key' => 'field_62bc2e7e7d15f',
                                            'label' => 'Hintergrundfarbe',
                                            'name' => 'dt_hintergrundfarbe',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                        array(
                                            'key' => 'field_62bc2e7e7d160',
                                            'label' => 'Textfarbe',
                                            'name' => 'dt_textfarbe',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62b95e24b673e' => array(
                                    'key' => 'layout_62b95e24b673e',
                                    'name' => 'kontaktformular',
                                    'label' => 'Kontaktformular (2 Spaltig)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62b9a3cae4f11' => array(
                                    'key' => 'layout_62b9a3cae4f11',
                                    'name' => 'ubersicht_inhalte_zeilen_bildtext_-_textbild',
                                    'label' => 'Übersicht Inhalte (Zeilen, Bild/Text - Text/Bild)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc357f6517a',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc5a4810b9a' => array(
                                    'key' => 'layout_62bc5a4810b9a',
                                    'name' => 'ubersicht_produkte_zeilen_bildtext_-_textbild',
                                    'label' => 'Übersicht Produkte (Zeilen, Bild/Text - Text/Bild)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc5a4810b9b',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc5a5410b9c' => array(
                                    'key' => 'layout_62bc5a5410b9c',
                                    'name' => 'ubersicht_blognews_zeilen_bildtext_-_textbild',
                                    'label' => 'Übersicht Blog/News (Zeilen, Bild/Text - Text/Bild)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc5a5410b9d',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc5d9493944' => array(
                                    'key' => 'layout_62bc5d9493944',
                                    'name' => 'mitarbeiter',
                                    'label' => 'Mitarbeiter',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc5d9493945',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                        array(
                                            'key' => 'field_62bc66e8baad7',
                                            'label' => 'Farbüberlagerung',
                                            'name' => 'farbuberlagerung',
                                            'type' => 'color_picker',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'enable_opacity' => 1,
                                            'return_format' => 'string',
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62b9adf6c1914' => array(
                                    'key' => 'layout_62b9adf6c1914',
                                    'name' => 'ubersicht_inhalte_text',
                                    'label' => 'Übersicht Inhalte (Text)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc35a90190d',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc945d16529' => array(
                                    'key' => 'layout_62bc945d16529',
                                    'name' => 'ubersicht_produkte_text',
                                    'label' => 'Übersicht Produkte (Text)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc945d1652a',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc94701652b' => array(
                                    'key' => 'layout_62bc94701652b',
                                    'name' => 'ubersicht_blognews_text',
                                    'label' => 'Übersicht Blog/News (Text)',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc94701652c',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc6f6e681e2' => array(
                                    'key' => 'layout_62bc6f6e681e2',
                                    'name' => 'rezessionen',
                                    'label' => 'Rezessionen',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc6f6e681e3',
                                            'label' => 'Überschrift für Block',
                                            'name' => 'uberschrift_fur_block',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => 'br',
                                            'acfe_textarea_code' => 0,
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                                'layout_62bc76ac32481' => array(
                                    'key' => 'layout_62bc76ac32481',
                                    'name' => 'kontaktformular_mit_google_maps',
                                    'label' => 'Kontaktformular mit Google Maps',
                                    'display' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_62bc76c532482',
                                            'label' => 'Google Maps mit Kontaktformular',
                                            'name' => 'gmaps_mit_kontaktformular',
                                            'type' => 'select',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'choices' => array(
                                                '[elementor-template id="1703"]' => 'Google Maps mit Kontaktformular',
                                            ),
                                            'default_value' => false,
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                            'ui' => 0,
                                            'return_format' => 'value',
                                            'ajax' => 0,
                                            'placeholder' => '',
                                        ),
                                    ),
                                    'min' => '',
                                    'max' => '',
                                    'acfe_flexible_render_template' => false,
                                    'acfe_flexible_render_style' => false,
                                    'acfe_flexible_render_script' => false,
                                    'acfe_flexible_thumbnail' => false,
                                    'acfe_flexible_settings' => false,
                                    'acfe_flexible_settings_size' => 'medium',
                                    'acfe_flexible_modal_edit_size' => false,
                                    'acfe_flexible_category' => false,
                                ),
                            ),
                            'button_label' => 'SEKTION HINZUFÜGEN',
                            'min' => 1,
                            'max' => 15,
                            'acfe_flexible_layouts_previews' => false,
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'options_page',
                                'operator' => '==',
                                'value' => '3d-struktur',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'seamless',
                    'label_placement' => 'left',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => array(
                        0 => 'permalink',
                        1 => 'block_editor',
                        2 => 'the_content',
                        3 => 'excerpt',
                        4 => 'discussion',
                        5 => 'comments',
                        6 => 'revisions',
                        7 => 'slug',
                        8 => 'author',
                        9 => 'format',
                        10 => 'page_attributes',
                        11 => 'featured_image',
                        12 => 'categories',
                        13 => 'tags',
                        14 => 'send-trackbacks',
                    ),
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                    'acfe_display_title' => '',
                    'acfe_autosync' => '',
                    'acfe_form' => 0,
                    'acfe_meta' => '',
                    'acfe_note' => '',
                ));
                
                endif;		